<!-- Latest compiled and minified CSS & JS -->
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<h3 style="text-align: center"> REVIEW </h3>

<div role="tabpanel">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active">
			<a href="#php" aria-controls="PHP" role="tab" data-toggle="tab">PHP</a>
		</li>
		<li role="presentation">
			<a href="#javascript" aria-controls="Javascript" role="tab" data-toggle="tab">Javascript</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div class="container">

			<div role="tabpanel" class="tab-pane active" id="php">
			<?php echo('hello php');?>
			heelo
			</div>
			<div role="tabpanel" class="tab-pane" id="javascript">

			</div>
		</div>
	</div>
</div>

