<!-- Latest compiled and minified CSS & JS -->
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<!DOCTYPE html>
<html>
<head>
	<title>REVIEW</title>
</head>
<body style="">
<h4 style="text-align: center"> REVIEW </h4>

<div role="tabpanel">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist" style="font-family: courier new; font-weight: bold; font-size: 16px;">
		<li role="presentation" class="active">
			<a href="#php" aria-controls="PHP" role="tab" data-toggle="tab">PHP Basic</a>
		</li>
		<li role="presentation">
			<a href="#codeigniter" aria-controls="codeigniter" role="tab" data-toggle="tab">PHP Codeigniter</a>
		</li>
		<li role="presentation">
			<a href="#CBFW" aria-controls="CBFW" role="tab" data-toggle="tab">PHP CBFW</a>
		</li>
		<li role="presentation">
			<a href="#javascript" aria-controls="Javascript" role="tab" data-toggle="tab">Javascript</a>
		</li>
		<li role="presentation">
			<a href="#jquery" aria-controls="jquery" role="tab" data-toggle="tab">jQuery</a>
		</li>
		<li role="presentation">
			<a href="#mysql" aria-controls="regex" role="tab" data-toggle="tab">Database mysql</a>
		</li>
		<li role="presentation">
			<a href="#linux" aria-controls="linux" role="tab" data-toggle="tab">Linux CentOS</a>
		</li>
		<li role="presentation">
			<a href="#regex" aria-controls="regex" role="tab" data-toggle="tab">Regular Expression and htaccess</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content container">
	<br>
		<div role="tabpanel" class="tab-pane active" id="php">
			<?php include 'review/php.phtml'; ?>

		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="codeigniter">
			<?php include 'review/ci.phtml'; ?>
		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="CBFW">
			<?php include 'review/cbfw.phtml'; ?>

		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="javascript">
			<?php include 'review/javascript.phtml'; ?>
		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="jquery">
			<?php include 'review/jquery.phtml'; ?>
		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="mysql">
			<?php include 'review/mysql.phtml'; ?>
		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="linux">
			<?php include 'review/linux.phtml'; ?>
		</div>


		<!-- --------------------------------------------------------------------------------------------------------------------------------- -->
		<div role="tabpanel" class="tab-pane" id="regex">
			<?php include 'review/regex.phtml'; ?>
		</div>
	</div>
</div>
</body>
</html>

