<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>1 số hàm hay xử lý trong controller</b></button>
	<button type="button" class="btn btn-default">outputCSV (Action)</button>
	<button type="button" class="btn btn-default">deleteObject (DbTableAbstract)</button>
	<button type="button" class="btn btn-default"> </button>
	<button type="button" class="btn btn-default">autoUpdate (DbTableAbstract)</button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
</div>

<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>Các vấn đề về Validate</b></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
</div>

<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>Các vấn đề về Smarty</b></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
</div>