<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>Debug JS với Chrome Dev Tools</b></button>
	<button type="button" class="btn btn-default">Kiểm soát luồng chạy bằng Breakpoints</button>
	<button type="button" class="btn btn-default">Console API</button>
	<button type="button" class="btn btn-default">Giải minify và làm đẹp code</button>
</div>

<div class="btn-group-vertical">
	<button type="button" class="btn btn-primary">T</button>
	<button type="button" class="btn btn-default">Middle</button>
	<button type="button" class="btn btn-default">Bottom</button>
</div>