<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>CBFW</b></button>
	<button type="button" class="btn btn-default">
		function getList(){<br>
		$colomns	= array("X_id, ...");
		$select		= $this->select($columns)->where("delete_flg = 0");<br>
		$return		= $this->fetchAll($select);<br>
		return $return;
	}
	</button>

	<button type="button" class="btn btn-default">
		function getbyID ($X_id){<br>
		$colomns	= array("X_id, ...");
		$select		= $this->select($columns)->where("X_id = ?, $X_id");<br>
		$return		= $this->fetchRow($select);<br>
		return $return;
	}
	</button>

	<button type="button" class="btn btn-default">
		function searchX ($param){<br>
		$colomns	= array("X_id, ...");
		$select		= $this->select($columns)->where("...");<br>
		if($param["data"]){
		$data = $param["data"];
		if($data['ten_field'] != ''){ // Trường hợp là textbox <br>
		$select->where($this->quoteInto("ten_DB =?", $data['ten_field']));<br>
	}
	if($data['ten_field']){ // Trường hợp datetime min <br>
	$select->where("date(ten_DB) >= ?", $data["ten_field"])
	}
	}
	$return		= $this->fetchRow($select);<br>
	return $return;
	}
	</button>

	<button type="button" class="btn btn-default">
		function lastInsertId(){<br>
		$return = $this->fetchRow("select X_id from table order by X_id desc limit 1");<br>
		return $return["X_id"]+1;
	}</button>

	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
</div>

<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>Codeigniter</b></button>
	<button type="button" class="btn btn-default">
		function getList(){<br>
		$colomns	= array("X_id, ...");
		$select		= $this->select($columns)->where("delete_flg = 0");<br>
		$return		= $this->fetchAll($select);<br>
		return $return;
	}
</button>
<button type="button" class="btn btn-default">
	function lastInsertId(){<br>
	$return = $this->fetchRow("select X_id from table order by X_id desc limit 1");<br>
	return $return["X_id"]+1;
}</button>
<button type="button" class="btn btn-default"></button>
<button type="button" class="btn btn-default"></button>
</div>