<div class="btn-group-vertical">
	<button type="button" class="btn btn-danger"><b>1 số hàm thông dụng</b></button>
	<button type="button" class="btn btn-default">pathinfo (path,options)</button>
	<button type="button" class="btn btn-default">file_exists (path)</button>
	<button type="button" class="btn btn-default">unlink (filename,context)</button>
	<button type="button" class="btn btn-default">in_array (search,array,type)</button>
	<button type="button" class="btn btn-default">unserialize and serialize</button>
	<button type="button" class="btn btn-default">array_search (value,array,strict)</button>
	<button type="button" class="btn btn-default">array_flip (array)</button>
	<button type="button" class="btn btn-default">array_filter (array,callbackfunction)</button>
	<button type="button" class="btn btn-default">rename (oldname,newname,context)</button>
	<button type="button" class="btn btn-default">implode and explode</button>
	<button type="button" class="btn btn-default">json_encode and json_decode</button>
	<button type="button" class="btn btn-default">array_diff</button>
	<button type="button" class="btn btn-default">ksort</button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
	<button type="button" class="btn btn-default"></button>
</div>